# Use the official PostgreSQL image as the base image
FROM postgres:latest

# Set environment variables for the database
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=password
ENV POSTGRES_DB=gigalogy

# Expose the default PostgreSQL port
EXPOSE 5432